## Matroids in OSCAR


### Installing and updating Oscar

In julia press the `]` key.  The terminal will enter the Pkg REPL and will look like this. (note that I am running julia version 1.8)

```
(@v1.8) pkg> 
```

To return to the usual julia REPL `julia>`, press the `Backspace` button.  To install Oscar and Combinatorics, in the Pkg REPL, run

```
(@v1.8) pkg> add "Oscar"
```

Alternatively, in the julia REPL, run

```
julia> using Pkg
julia> Pkg.add("Oscar")
```

By asking julia to add Oscar, it will also install required packages like Polymake.jl and Singular.jl. To get the status and update all packages, run in the Pkg REPL

```
(@v1.8) pkg> status
(@v1.8) pkg> up
```

To use julia in a jupyter notebook, you must have the `IJulia` package. The package `Combinatorics` is also required for this notebook. You can add these in a similar way as with `Oscar`.  

### Getting help

To enter the help mode in a julia REPL, type `?`. The prompt will change to `help?`. You can enter the name of a function, and it will return its documentation. For example, here is a snipit of what you get when asking for help with the function `convex_hull`. 

```
help?> convex_hull
search: convex_hull

  convex_hull([::Type{T} = QQFieldElem,] V [, R [, L]]; non_redundant::Bool = false)

  Construct the convex hull of the vertices V, rays R, and lineality L. If R or L are omitted, then
  they are assumed to be zero.

  Arguments
  ≡≡≡≡≡≡≡≡≡≡≡

    •  V::AbstractCollection[PointVector]: Points whose convex hull is to be computed.

    •  R::AbstractCollection[RayVector]: Rays completing the set of points.

    •  L::AbstractCollection[RayVector]: Generators of the Lineality space.

  If an argument is given as a matrix, its content has to be encoded row-wise.

  R can be given as an empty matrix or as nothing if the user wants to compute the convex hull only
  from V and L.

  If it is known that V and R only contain extremal points and that the description of the
  lineality space is complete, set non_redundant = true to avoid unnecessary redundancy checks.

  See Def. 2.11 and Def. 3.1 of JT13 (@cite).
```

Another useful function `apropos`. If you have a string that you want to search for (or a related expression),  run 

```
julia> apropos(blah)
```

or in the help mode, use double quotes:

```
help?> "blah"
```

**Oscar manual**

- Stable release: https://docs.oscar-system.org/stable/

- Developers: https://docs.oscar-system.org/dev/

In [1]:
using Oscar
using Combinatorics

 -----    -----    -----      -      -----   
|     |  |     |  |     |    | |    |     |  
|     |  |        |         |   |   |     |  
|     |   -----   |        |     |  |-----   
|     |        |  |        |-----|  |   |    
|     |  |     |  |     |  |     |  |    |   
 -----    -----    -----   -     -  -     -  

...combining (and extending) ANTIC, GAP, Polymake and Singular
Version 0.12.0-DEV ... 
 ... which comes with absolutely no warranty whatsoever
Type: '?Oscar' for more information
(c) 2019-2023 by The OSCAR Development Team


## Matroids

A $(d,n)$-*matroid* is a nonempty subset $\mathsf{Q} \subset \binom{[n]}{d}$ that satisfies the basis-exchange axiom: for any $A, B \in \mathsf{Q}$ and $a\in A\setminus B$, there is a $b\in B\setminus A$ such that $A \Delta \{a,b\} \in \mathsf{Q}$. The elements of $\mathsf{Q}$ are called the *bases* of $\mathsf{Q}$.

The *M&ouml;bius-Kantor* matroid $\mathsf{Q}_{mk}$ is the rank 3 matroid on $[8]$ whose bases are $\binom{[8]}{3}$ except for the following subsets
\begin{equation}
126, 145, 178, 235, 248, 347, 368, 567.
\end{equation}
Geometrically, this is the matroid of the configuration of 8 points (and lines) in $\mathbb{P}^{2}$ such that every point is contained in 3 lines and every line contains 3 points. 

In [2]:
MK = matroid_from_nonbases([[1,2,6],[1,4,5],[1,7,8],[2,3,5],[2,4,8],[3,4,7],[3,6,8],[5,6,7]], 8)

Matroid of rank 3 on 8 elements

Define the $(4,8)$-matroid $\mathsf{Q}_{\text{oct}}$ to be the matroid of the supporting hyperplanes of the regular octahedron in $\mathbb{P}^{3}$. 

In [3]:
A = matrix(ZZ,
    [1 -1 -1 -1;
     1 1 -1 -1;
     1 -1 1 -1;
     1 1 1 -1;
     1 -1 -1 1;
     1 1 -1 1;
     1 -1 1 1;
     1 1 1 1])

Oct = matroid_from_matrix_rows(A)

Matroid of rank 4 on 8 elements

Running functions like `bases`, `nonbases`, `circuits`, `flats`, etc. gives the basic data of the matroid. For example, the bases of $\mathsf{Q}_{\text{oct}}$ are $\binom{[8]}{4}$ except
\begin{equation}
    1234, 1256, 1278, 1357, 1368, 1458, 2367, 2457, 2468, 3456, 3478, 5678
\end{equation}

In [4]:
nonbases(Oct)

12-element Vector{Vector{Int64}}:
 [1, 2, 3, 4]
 [1, 2, 5, 6]
 [1, 2, 7, 8]
 [1, 3, 5, 7]
 [1, 3, 6, 8]
 [1, 4, 5, 8]
 [2, 3, 6, 7]
 [2, 4, 5, 7]
 [2, 4, 6, 8]
 [3, 4, 5, 6]
 [3, 4, 7, 8]
 [5, 6, 7, 8]

### Automorphism groups
Next, we compute the automorphism group of $\mathsf{Q}_{mk}$. 

In [5]:
AutMK = automorphism_group(MK);
@show AutMK;
@show order(AutMK);

AutMK = Group([ (1,3)(4,8)(5,6), (1,7,3,2)(4,5,6,8), (1,3)(2,4)(6,7) ])
order(AutMK) = 48


For well-known groups, the function `describe` gives a familiar description of the group.

In [6]:
@show describe(AutMK);

describe(AutMK) = "GL(2,3)"


An explanation of the notation can be found here

https://docs.oscar-system.org/dev/Groups/basics/#describe-Tuple{Oscar.GAPGroup}

In this case, `GL(2,3)` means $\mathsf{GL}_2(\mathbb{F}_3)$. Here is the automorphism group for $\mathsf{Q}_{\text{oct}}$.

In [7]:
AutOct = automorphism_group(Oct);
@show AutOct;
@show order(AutOct);

AutOct = Group([ (1,7)(3,5), (2,3)(6,7), (1,4)(6,7), (1,2)(3,4)(5,6)(7,8) ])
order(AutOct) = 192


In [8]:
@show describe(AutOct);

describe(AutOct) = "(((C2 x C2 x C2 x C2) : C3) : C2) : C2"


Here, `N:H` denotes the semidirect product $N \rtimes H$. Here are some automorphism groups of famous matroids.

In [9]:
@show describe(automorphism_group(non_fano_matroid()));
@show describe(automorphism_group(fano_matroid()));
@show describe(automorphism_group(non_pappus_matroid()));
@show describe(automorphism_group(pappus_matroid()));
@show describe(automorphism_group(vamos_matroid()));

describe(automorphism_group(non_fano_matroid())) = "S4"
describe(automorphism_group(fano_matroid())) = "PSL(3,2)"
describe(automorphism_group(non_pappus_matroid())) = "D12"
describe(automorphism_group(pappus_matroid())) = "((C3 x C3) : C3) : (C2 x C2)"
describe(automorphism_group(vamos_matroid())) = "D8 x D8"


**Fact**. The automorphism group of a graph $\Gamma$ is not in general isomorphic to the automorphism group of its cycle matroid. 

In [10]:
Gamma = complete_graph(4)
rem_edge!(Gamma, 3, 4)
S4 = symmetric_group(4)
gensG = automorphism_group_generators(Gamma)
G_graph, _ = sub(S4, gensG)
@show describe(G_graph);

describe(G_graph) = "C2 x C2"


In [11]:
MGamma = cycle_matroid(Gamma)
G_mat = automorphism_group(MGamma)
@show describe(G_mat);

describe(G_mat) = "D8"


### Matroid polytopes
Let $\epsilon_1,\ldots,\epsilon_n$ denote the standard basis of $\mathbb{R}^n$. Given a $(d,n)$-matroid $\mathsf{Q}$, the matroid polytope of $\mathsf{Q}$ is 

\begin{equation}
\Delta(\mathsf{Q}) = \mathsf{conv}(\epsilon_{i_1} + \cdots + \epsilon_{i_d} \, : \, \{\epsilon_{i_1}, \ldots, \epsilon_{i_d}\} \in \mathsf{Q})
\end{equation}

In [12]:
function indicator(B, n)
    v = zeros(Int, n)
    w = ones(Int, length(B))
    v[B] = w
    return v
end

function matroid_polytope(Q)
    Bs = bases(Q)
    n = length(matroid_groundset(Q))
    eBs = [indicator(B,n) for B in Bs]
    vs =[eBs[i][j] for i in 1:length(Bs), j in 1:n]
    return convex_hull(vs)
end

matroid_polytope (generic function with 1 method)

The matroid polytope $\Delta(\mathsf{Q})$ has dimension $n-\#(\text{connected components})$. Given a connected matroid $\mathsf{Q}$, a subset $A$ is nondegenerate if the restriction $\mathsf{Q}|A$ and contraction $\mathsf{Q}/A$ are connected. The hyperplane description of $\Delta(\mathsf{Q})$ is

\begin{align}
    &x_{1} + \cdots + x_n = d \\
    &\sum_{i\in I}x_{i} \leq r_{\mathsf{Q}}(I) \hspace{20pt} \text{ if $I$ is a nondegenerate subset}.
\end{align}





In [13]:
Delta = matroid_polytope(MK)
facets(Delta)

24-element SubObjectIterator{AffineHalfspace{QQFieldElem}} over the Halfspaces of R^8 described by:
-x₆ ≦ 0
-x₈ ≦ 0
-x₃ - x₄ - x₅ - x₇ - x₈ ≦ -1
-x₂ - x₃ - x₄ - x₅ - x₆ - x₇ - x₈ ≦ -2
x₂ ≦ 1
-x₇ ≦ 0
-x₅ ≦ 0
x₂ + x₃ + x₅ ≦ 2
x₃ ≦ 1
-x₄ ≦ 0
x₂ + x₄ + x₈ ≦ 2
x₄ ≦ 1
x₃ + x₆ + x₈ ≦ 2
-x₂ - x₃ - x₆ - x₇ - x₈ ≦ -1
x₅ ≦ 1
x₂ + x₃ + x₄ + x₅ + x₆ + x₇ + x₈ ≦ 3
-x₂ - x₃ - x₄ - x₅ - x₆ ≦ -1
-x₃ ≦ 0
x₇ ≦ 1
-x₂ ≦ 0
x₃ + x₄ + x₇ ≦ 2
x₈ ≦ 1
x₅ + x₆ + x₇ ≦ 2
x₆ ≦ 1


Reintrepreting this, we see that the facets are 
\begin{align} 
    \begin{array}{ll}
     x_i \leq 1 & \text{ for } i=1,\ldots,8\\
     \sum_{j\neq i} x_j \leq 3 & \text{ for } i=1,\ldots,8 \\
     x_{i} + x_{j} + x_{k} \leq 2 & \text{ for } ijk = 126, 145, 178, 235, 248, 347, 368, 567.
    \end{array}
\end{align}
This agrees with the description above, indeed, the nondegenerate subsets of $\mathsf{Q}_{mk}$ are the singletons, sets of size 7, and the nonbases of this matroid (warning: this nonbases characterization does not generalize).

In [14]:
nondegenerate = [[1], [2], [3], [4], [5], [6], [7], 
    [1,2,6], [1,4,5], [1,7,8], [2,3,5], [2,4,8], [3,4,7], [3,6,8], [5,6,7],
    [1,2,3,4,5,6,7], [1,2,3,4,5,6,7], [1,2,3,4,5,6,8], [1,2,3,4,5,7,8], [1,2,3,4,6,7,8], 
    [1,2,3,5,6,7,8], [1,2,4,5,6,7,8], [1,3,4,5,6,7,8], [2,3,4,5,6,7,8]];

all([is_connected(restriction(MK,A)) && is_connected(contraction(MK,A))  for A in nondegenerate ])

true

### Regular subdivisions 

Given a polytope $\Delta \subset \mathbb{R}^{n}$ (more generally, a point configuration) and a function on the vertices $\mathsf{w}\in \mathbb{R}^{V(\Delta)}$, we may form the regular subdivision of $\Delta$, which we denote by $\mathcal{Q}(\mathsf{w})$. This subdivision is achieved by lifting the vertices of $\Delta \subset \mathbb{R}^n \times \mathbb{R}$ to heights dictated by $\mathsf{w}$, then project the lowerfaces to $\Delta$. 

The hypersimplex $\Delta(d,n)$ is the convex hull of the indicator vectors of all elements in $\binom{[n]}{d}$. If $d=1$ or $d=n-1$, this is just an ordinary simplex. 

In [15]:
Delta48 = matroid_polytope(uniform_matroid(4,8))
V48 = vertices(Delta48)

70-element SubObjectIterator{PointVector{QQFieldElem}}:
 [1, 1, 1, 1, 0, 0, 0, 0]
 [1, 1, 1, 0, 1, 0, 0, 0]
 [1, 1, 1, 0, 0, 1, 0, 0]
 [1, 1, 1, 0, 0, 0, 1, 0]
 [1, 1, 1, 0, 0, 0, 0, 1]
 [1, 1, 0, 1, 1, 0, 0, 0]
 [1, 1, 0, 1, 0, 1, 0, 0]
 [1, 1, 0, 1, 0, 0, 1, 0]
 [1, 1, 0, 1, 0, 0, 0, 1]
 [1, 1, 0, 0, 1, 1, 0, 0]
 [1, 1, 0, 0, 1, 0, 1, 0]
 [1, 1, 0, 0, 1, 0, 0, 1]
 [1, 1, 0, 0, 0, 1, 1, 0]
 ⋮
 [0, 0, 1, 1, 0, 1, 1, 0]
 [0, 0, 1, 1, 0, 1, 0, 1]
 [0, 0, 1, 1, 0, 0, 1, 1]
 [0, 0, 1, 0, 1, 1, 1, 0]
 [0, 0, 1, 0, 1, 1, 0, 1]
 [0, 0, 1, 0, 1, 0, 1, 1]
 [0, 0, 1, 0, 0, 1, 1, 1]
 [0, 0, 0, 1, 1, 1, 1, 0]
 [0, 0, 0, 1, 1, 1, 0, 1]
 [0, 0, 0, 1, 1, 0, 1, 1]
 [0, 0, 0, 1, 0, 1, 1, 1]
 [0, 0, 0, 0, 1, 1, 1, 1]

In this setup, the vertices are labeled lexicographically. Given $B = \{i_1,\ldots,i_d\}$, let $\mathsf{e}_{B} = \epsilon_{i_1} \wedge \cdots \wedge \epsilon_{i_d}$. The vectors $e_{B}$ for $B\in \binom{[n]}{d}$ form a basis for $\wedge^d\mathbb{R}^{n} \cong \mathbb{R}^{\textstyle{\binom{[8]}{4}}}$. We compute the regular subdivision of $\Delta(4,8)$ with respect to the vector 
\begin{equation*}
\mathsf{w} = \mathsf{e}_{1234} + \mathsf{e}_{1256} + \mathsf{e}_{1278} + \mathsf{e}_{1357} + \mathsf{e}_{1368} +  \mathsf{e}_{1458} + \mathsf{e}_{2367} + \mathsf{e}_{2457} + \mathsf{e}_{2468} + \mathsf{e}_{3456} + \mathsf{e}_{3478} + \mathsf{e}_{5678} \in \mathbb{R}^{\textstyle{\binom{[8]}{4}}}.
\end{equation*}

In [16]:
C48 = collect(powerset(1:8, 4, 4))
w = [4-rank(Oct, B) for B in C48]
Qw = SubdivisionOfPoints(V48, w)
maxQw = maximal_cells(Qw)

13-element SubObjectIterator{Vector{Int64}}:
 [2, 3, 6, 7, 10, 11, 12, 13, 14, 20, 26, 32, 33, 40, 46, 52, 53]
 [2, 4, 11, 16, 18, 20, 21, 22, 23, 25, 27, 32, 34, 41, 57, 62, 64]
 [3, 5, 14, 17, 19, 20, 22, 23, 24, 25, 30, 33, 35, 44, 60, 63, 65]
 [4, 5, 8, 9, 11, 12, 13, 14, 15, 25, 31, 34, 35, 45, 51, 54, 55]
 [18, 19, 25, 31, 38, 39, 45, 51, 57, 58, 59, 60, 61, 64, 65, 68, 69]
 [32, 33, 34, 35, 52, 53, 54, 55, 62, 63, 64, 65, 66, 67, 68, 69, 70]
 [6, 9, 12, 16, 19, 22, 26, 27, 28, 30, 31, 33, 34, 48, 58, 67, 68]
 [16, 17, 20, 26, 36, 37, 40, 46, 56, 57, 58, 59, 60, 62, 63, 66, 67]
 [7, 9, 14, 30, 37, 39, 44, 46, 48, 49, 50, 51, 53, 55, 60, 67, 69]
 [6, 8, 11, 27, 36, 38, 41, 46, 47, 48, 49, 51, 52, 54, 57, 66, 68]
 [2, 3, 4, 5, 6, 7, 8, 9, 11, 12  …  59, 60, 62, 63, 64, 65, 66, 67, 68, 69]
 [3, 4, 13, 23, 37, 38, 40, 41, 43, 44, 45, 49, 52, 55, 59, 62, 65]
 [1, 2, 3, 4, 5, 6, 7, 8, 9, 16, 17, 18, 19, 36, 37, 38, 39]

A good way to visualize a regular subdivision is via its adjacency graph. Unfortunately, this command is not yet in Oscar, so we must work with Polymake.jl. 

In [17]:
graph_polymake = Qw.pm_subdivision.POLYHEDRAL_COMPLEX.DUAL_GRAPH
graph_oscar = Graph{Graphs.Undirected}(graph_polymake.ADJACENCY);

The problem is that Polymake.jl is `0`-based, whereas julia is `1`-based indexed. Sometimes, the functions `Polymake.to_one_based_indexing` and `Polymake.to_zero_based_indexing` are useful to convert between the two conventions. 

To visualize the graph, use the function `Polymake.visual`.

In [18]:
Polymake.visual(graph_polymake)

Here is a more interesting subdivision, this time for $\Delta(3,8)$. Let 
\begin{align}
\mathsf{w} = &2\mathsf{e}_{123} + 2\mathsf{e}_{124} + 2\mathsf{e}_{134} + 2\mathsf{e}_{135} + 2\mathsf{e}_{136} + 4\mathsf{e}_{137} + 3\mathsf{e}_{138} + \mathsf{e}_{156}  + \mathsf{e}_{178} + 2\mathsf{e}_{234} + \mathsf{e}_{245} + \mathsf{e}_{246} + \\
&\mathsf{e}_{247}  + \mathsf{e}_{248} + \mathsf{e}_{256} + \mathsf{e}_{278} + \mathsf{e}_{356}  + \mathsf{e}_{378} + \mathsf{e}_{456} + \mathsf{e}_{478} +  2\mathsf{e}_{567}  + 2\mathsf{e}_{568} +  2\mathsf{e}_{578} + 2\mathsf{e}_{678} 
\end{align}

In [19]:
Delta38 = matroid_polytope(uniform_matroid(3,8))
V38 = vertices(Delta38)
w2 = [2,2,0,0,0,0,2,2,2,4,3,0,0,0,0,1,0,0,0,0,1,2,0,0,0,0,1,1,
      1,1,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,1,0,0,0,0,1,2,2,2,2]
Qw2 = SubdivisionOfPoints(V38, w2)
graph_polymake2 = Qw2.pm_subdivision.POLYHEDRAL_COMPLEX.DUAL_GRAPH;

In [20]:
Polymake.visual(graph_polymake2)

The *secondary fan* $\Sigma_{\text{sec}}(\Delta)$ is the complete fan in $\mathbb{R}^{V(\Delta)} / \mathbb{R}$, where two vectors $\mathsf{w}$ and $\mathsf{w}'$ belong to the relative interior of the same cone if and only if $\mathcal{Q}(\mathsf{w}) = \mathcal{Q}(\mathsf{w}')$. The function `secondary_cone` returns the cone in the secondary fan corresponding to the input regular subdivision. 

In [21]:
Cw = secondary_cone(Qw)
@show dim(Cw);

dim(Cw) = 20


If $\Delta$ is full dimensional in $\mathbb{R}^n$ (which is *not* the case for the $(d,n)$-hypersimplex), the secondary fan has a $n$-dimensional lineality space induced by all linear functions on $\mathbb{R}^n$. So to get the rays of this cone, use the `rays_modulo_lineality` function. 

In [22]:
rays_w, lineality_w = rays_modulo_lineality(Cw)
rays_w

12-element SubObjectIterator{RayVector{QQFieldElem}}:
 [0, -1, -1, -1, 0, -1, -1, -1, 0, -1  …  0, -1, 0, 0, 0, -1, 0, 0, 0, 0]
 [0, 1, -1, 1, -1, 1, -1, 1, -1, 0  …  0, 1, -1, 1, -1, 1, -1, 1, -1, 0]
 [0, 1, 1, 0, 1, 0, 0, -1, 0, 1  …  0, 0, 1, 0, 0, -1, 0, -1, -1, 0]
 [0, -1, -1, -1, 1, -1, -1, -1, 1, -2  …  0, -3, -1, -1, -1, -3, -1, -1, -1, 0]
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0  …  0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
 [0, 1, 1, 1, 1, -1, -1, -1, -1, 0  …  0, 1, 1, 1, 1, -1, -1, -1, -1, 0]
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0  …  0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0  …  0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
 [0, -1, 1, -1, -1, -1, 1, -1, -1, 0  …  0, 1, 1, -1, 1, 1, 1, -1, 1, 0]
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0  …  0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0  …  0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 1  …  0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

Ugh, these vector representatives are not the cleanest. To find the simpliest representative of a vector in the secondary cone of a regular subdivision, use the `min_weights` function. Here is how this works for the first ray. 

In [23]:
println(min_weights(SubdivisionOfPoints(Delta48, rays_w[1])))

[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


We can use this to confirm that the rays of this secondary cone are $\mathsf{e}_{1234}, \mathsf{e}_{1256}, \mathsf{e}_{1278}, \mathsf{e}_{1357}, \mathsf{e}_{1368}, \mathsf{e}_{1458}, \mathsf{e}_{2367}, \mathsf{e}_{2457}, \mathsf{e}_{2468}, \mathsf{e}_{3456}, \mathsf{e}_{3478}, \mathsf{e}_{5678}$.

In [24]:
vcat([min_weights(SubdivisionOfPoints(Delta48, r))' for r in rays_w]...)

12×70 Matrix{Int64}:
 1  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  1  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  1
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  1  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0

### Matroidal subdivisions and the tropical Grassmannian

A regular subdivision $\mathcal{Q}$ of $\Delta(d,n)$ is *matroidal* if every cell in $\mathcal{Q}$ is the polytope of a matroid. Since the face of a matroid polytope is a matroid polytope by <a href="https://doi.org/10.1016/0001-8708(87)90059-4">Gelfand, Goresky, MacPherson, Serganova 1987</a>.

*Tropical Grassmannian*: $\mathsf{TGr}{^\circ}(d,n)$ the tropicalization of the open cell in the Grassmannian $\mathsf{Gr}(d,n)$ defined by the nonvanishing of all Pl&uuml;cker coordinates. 

*Dressian*: $\mathsf{Dr}(d,n) = \{\mathsf{w} \in \mathbb{R}^{\textstyle{\binom{[n]}{d}}} / \mathbb{R} \, : \, \mathcal{Q}(\mathsf{w}) \text{ is matroidal} \}$. Naturally, the Dressian is the support of a subfan of $\Sigma_{\text{sec}}(\Delta(d,n))$

**Theorem** (<a href="https://doi.org/10.1137/080716219">Speyer 2004</a>, <a href="https://doi.org/10.37236/72 "> Herrmann, Jensen, Joswig, Sturmfels 2008</a>) The tropical Grassmannian $\mathsf{TGr}^{\circ}(d,n)$ is a subset of $\mathsf{Dr}(d,n)$. In particular, $\mathcal{Q}(\mathsf{w})$ is matroidal for $\mathsf{w} \in \mathsf{TGr}^{\circ}(d,n)$. This inclusion is typically strict. In fact, $\dim \mathsf{TGr}{^\circ}(d,n) = d(n-d)$, but $\mathsf{Dr}(d,n)$ grows quadratically with $n$. 

Consider the corank vector `w` of $\mathsf{Q}_{\text{oct}}$ from before. The subdivision $\mathcal{Q}(\mathsf{w})$ is matroidal. Recall that the dual graph of $\mathcal{Q}(\mathsf{w})$ is a star tree. The central node is $\mathsf{Q}_{\text{oct}}$, and the leaf nodes are each isomorphic to the the $(4,8)$ matroid with rank 1 flats $1,2,3,4,5678$, and its simplification is $U(4,5)$. 

In [25]:
matsQw = [matroid_from_bases(C48[C], 8) for C in maxQw];
Leaf = matroid_from_bases([[1,2,3,4],[1,2,3,5],[1,2,3,6],[1,2,3,7],[1,2,3,8],
        [1,2,4,5],[1,2,4,6],[1,2,4,7],[1,2,4,8],[1,3,4,5],[1,3,4,6],
        [1,3,4,7],[1,3,4,8],[2,3,4,5],[2,3,4,6],[2,3,4,7],[2,3,4,8]], 8)
@show is_isomorphic(matsQw[11], Oct)
@show all([is_isomorphic(matsQw[i], Leaf) for i in [1,2,3,4,5,6,7,8,9,10,12,13] ]);

is_isomorphic(matsQw[11], Oct) = true
all([is_isomorphic(matsQw[i], Leaf) for i = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13]]) = true


The secondary cone `Cw` containing `w` has dimension 19 (in $\mathbb{R}^{\textstyle{\binom{[8]}{4}}}/\mathbb{R}$), but $\dim \mathsf{TGr}^{\circ}(4,8) = 16$, so $\mathsf{TGr}^{\circ}(4,8)$ is properly contained in $\mathsf{Dr}(4,8)$. 

### Matroid strata of the Grassmannian and realization spaces

Given a field $K$ and a matroid $\mathsf{Q}$ realizable over $K$, its *matroid stratum* is the locally closed suscheme of the Grassmannian
\begin{equation}
    \mathsf{Gr}(\mathsf{Q}) = \{F \subset K^{n} \, : \, F \text{ is a realization of } \mathsf{Q}\}.
\end{equation}
When $\mathsf{Q}$ is connected, the diagonal torus $H\subset \mathsf{PGL(n)}$ acts freely on $\mathsf{Gr}(\mathsf{Q})$ and the quotient is isomorphic to $X(\mathsf{Q})$, the moduli space $n$ hyperplanes in $\mathbb{P}^{d-1}$ that realize $\mathsf{Q}$, up to $\mathsf{PGL(d)}$. The space $X(\mathsf{Q})$ is called the *realization space* of $\mathsf{Q}$.  By Mn&euml;v universality, the spaces $X(\mathsf{Q})$ satisfy Murphy's law in the sense of <a href="https://doi.org/10.1007/s00222-005-0481-9">Vakil 2004</a>. The matroid $\mathsf{Q}_{mk}$ is the smallest rank $3$ matroid whose realization space is not irreducible. 

The function `matroid_realization_space` takes as input a simple connected matroid, a subset `A` of $d+1$ points in general position, and a field. It returns a pair `(M,W)` where `M` is a $d\times n$ matrix of variables, and `W` is the coordinate ring of $\mathsf{Q}$. The columns of the matrix `M` are the normal vectors of hyperplanes realizing $\mathsf{Q}$. We set the the columns of `M` indexed by `A` equal to the projective identity. As each column represents a point in $\mathbb{P}^{d-1}$, we may set one of the nonzero entries equal to 1. The remaining nonzero entries are given a variable. The coordinate ring `W` of $X(\mathsf{Q})$ is obtained from the polynomial ring by
   - quotienting by the ideal generated by the minors `M` whose columns are indexed by the nonbases,
   - localizing by the multiplicative semigroup generated by the minors of `M` whose columns are indexed by the bases.
   
Consider $\mathsf{Q}_{mk}$. The points $1367$ are in general position. 

In [26]:
RMK = matroid_realization_space(MK,[1,3,6,7],QQ)
RMK[1]

[1   x_{1, 1}   0   x_{1, 2}   x_{1, 3}   0   1          0]
[0          0   1   x_{2, 2}   x_{2, 3}   0   1   x_{2, 4}]
[0          1   0          1          1   1   1          1]

`RMK[1]` is is the reference matrix `M`. 

In [27]:
R = base_ring(RMK[2])
x= gens(R)
I = modulus(RMK[2])
gens(I)

6-element Vector{MPolyLocRingElem{QQField, QQFieldElem, QQMPolyRing, QQMPolyRingElem, MPolyPowersOfElement{QQField, QQFieldElem, QQMPolyRing, QQMPolyRingElem}}}:
 x_{2, 2} - x_{2, 3}
 -x_{2, 4} + 1
 x_{1, 1} - x_{1, 3}
 x_{1, 1}*x_{2, 2} - x_{1, 1}*x_{2, 4} + x_{1, 2}*x_{2, 4}
 -x_{1, 2} + 1
 -x_{1, 3} + x_{2, 3}

`I` is the ideal of the coordinate ring `W`. Notice that
\begin{equation}
    \begin{array}{ccccc}
        x_{12} \equiv 1 & x_{22} \equiv x_{11} & x_{13} \equiv x_{11} & x_{23} \equiv x_{11} & x_{24} \equiv 1
    \end{array} \mod I
\end{equation}
so we may perform these substitutions to produce a simplier expression for this ring. 

In [28]:
phi = hom(R, R, [x[1], 1, x[1], x[1], x[1], 1])
f = numerator(gens(I)[4])
phi(f)

x_{1, 1}^2 - x_{1, 1} + 1

The resulting ring has the form $S^{-1}\mathbb{Q}[x]/\langle x^{2} - x +1 \rangle$. After base changing to $\mathbb{C}$, this polynomial factors as $(x-\omega)(x-\bar{\omega})$ where $\omega$ and $\bar{\omega}$ are the primitive 6th roots of unity. This proves that $X(\mathsf{Q})$ has 2 connected components. 

## Polymake Database

The matroids with small rank and ground set can be found in the polymake database, see
-for an interactive version of the database https://db.polymake.org/
-for a tutorial on how to use the database https://polymake.org/doku.php/user_guide/howto/polydb_tutorial

Here is how we can collect all simple $(3,7)$-matroids.

In [29]:
db = Polymake.Polydb.get_db();
collection = db["Matroids.Small"];
cursor=Polymake.Polydb.find(collection, Dict("RANK" => 3, "SIMPLE"=>true, "N_ELEMENTS"=>7));

And here are their automorphism groups

In [30]:
i=1
for c in cursor
    M = Matroid(c)
    println(i, ": ", describe(automorphism_group(M)))
    i+=1
end

1: S7
2: S4 x S3
3: (S3 x S3) : C2
4: C2 x D8
5: D8
6: C2 x S4
7: S3
8: C2 x C2
9: S3
10: D12
11: S4
12: D8
13: S4
14: PSL(3,2)
15: S3 x S4
16: S3 x S4
17: D12
18: C2 x C2
19: S3
20: (S3 x S3) : C2
21: C2 x S5
22: C2 x S4
23: S6


Let's compute the characteristic polynomial of all binary $(4,9)$-matroids

In [31]:
db = Polymake.Polydb.get_db();
collection = db["Matroids.Small"];
cursor = Polymake.Polydb.find(collection, Dict("RANK" => 4, "N_LOOPS"=> 0, "BINARY"=>true, "N_ELEMENTS"=>9));

In [32]:
i=1
for c in cursor
    M = Matroid(c)
    println(i, ": ", characteristic_polynomial(M))
    i+=1
end

1: q^4 - 7*q^3 + 19*q^2 - 23*q + 10
2: q^4 - 7*q^3 + 17*q^2 - 17*q + 6
3: q^4 - 9*q^3 + 28*q^2 - 36*q + 16
4: q^4 - 8*q^3 + 21*q^2 - 22*q + 8
5: q^4 - 8*q^3 + 24*q^2 - 31*q + 14
6: q^4 - 8*q^3 + 23*q^2 - 28*q + 12
7: q^4 - 8*q^3 + 23*q^2 - 28*q + 12
8: q^4 - 8*q^3 + 23*q^2 - 28*q + 12
9: q^4 - 7*q^3 + 17*q^2 - 17*q + 6
10: q^4 - 7*q^3 + 19*q^2 - 23*q + 10
11: q^4 - 7*q^3 + 18*q^2 - 20*q + 8
12: q^4 - 7*q^3 + 18*q^2 - 20*q + 8
13: q^4 - 7*q^3 + 19*q^2 - 23*q + 10
14: q^4 - 7*q^3 + 18*q^2 - 20*q + 8
15: q^4 - 6*q^3 + 13*q^2 - 12*q + 4
16: q^4 - 6*q^3 + 14*q^2 - 15*q + 6
17: q^4 - 6*q^3 + 15*q^2 - 17*q + 7
18: q^4 - 6*q^3 + 14*q^2 - 15*q + 6
19: q^4 - 5*q^3 + 10*q^2 - 9*q + 3
20: q^4 - 7*q^3 + 19*q^2 - 23*q + 10
21: q^4 - 7*q^3 + 18*q^2 - 20*q + 8
22: q^4 - 7*q^3 + 18*q^2 - 20*q + 8
23: q^4 - 7*q^3 + 19*q^2 - 23*q + 10
24: q^4 - 7*q^3 + 18*q^2 - 20*q + 8
25: q^4 - 7*q^3 + 18*q^2 - 20*q + 8
26: q^4 - 7*q^3 + 18*q^2 - 20*q + 8
27: q^4 - 7*q^3 + 18*q^2 - 20*q + 8
28: q^4 - 6*q^3 + 14*q^2 - 1

## Commands I wish I knew earlier

`print` is the usual print, but `println` adds a new line at the end. 

In [33]:
print("a", "b"); print("c")

abc

In [34]:
println("a", "b"); println("c")

ab
c


Generate matrix with for loops.

In [35]:
[string(i,j) for i in 1:4, j in 1:7]

4×7 Matrix{String}:
 "11"  "12"  "13"  "14"  "15"  "16"  "17"
 "21"  "22"  "23"  "24"  "25"  "26"  "27"
 "31"  "32"  "33"  "34"  "35"  "36"  "37"
 "41"  "42"  "43"  "44"  "45"  "46"  "47"

More generally, combined for loops.

In [36]:
v = Matrix(undef, 4, 7)
for i in 1:4, j in 1:7
    v[i,j] = string(i,j)
end
v

4×7 Matrix{Any}:
 "11"  "12"  "13"  "14"  "15"  "16"  "17"
 "21"  "22"  "23"  "24"  "25"  "26"  "27"
 "31"  "32"  "33"  "34"  "35"  "36"  "37"
 "41"  "42"  "43"  "44"  "45"  "46"  "47"

Concatenate a list of vectors into a matrix using `hcat` and `vcat`. If you have a array of arrays `L`, place the string `...` after `L` to contatenate the entries of `L`.  

In [37]:
vs = [[string(i,j) for i in 1:4] for j in 1:7]

7-element Vector{Vector{String}}:
 ["11", "21", "31", "41"]
 ["12", "22", "32", "42"]
 ["13", "23", "33", "43"]
 ["14", "24", "34", "44"]
 ["15", "25", "35", "45"]
 ["16", "26", "36", "46"]
 ["17", "27", "37", "47"]

In [38]:
v2 = hcat(vs...)
v2

4×7 Matrix{String}:
 "11"  "12"  "13"  "14"  "15"  "16"  "17"
 "21"  "22"  "23"  "24"  "25"  "26"  "27"
 "31"  "32"  "33"  "34"  "35"  "36"  "37"
 "41"  "42"  "43"  "44"  "45"  "46"  "47"